name: Backend CI

on:
  push:
    paths:
      - 'src/ChatAzure.API/**'
      - 'src/ChatAzure.Core/**'
      - 'src/ChatAzure.Services/**'
    branches: [ develop, feature/*, release/* ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore --configuration Release
        
      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
        
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        
      - name: Run Security Scan
        uses: github/codeql-action/analyze@v2
        with:
          languages: csharp
          
  analyze:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}